# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Coefficient of Variation (Rcpp implementation)
#' 
#' Computes the coefficient of variation (sd/mean) for a numeric vector.
#' This is a high-performance replacement for the pure R version.
#' 
#' @param x Numeric vector
#' @param na_rm Should NA values be removed? Default TRUE
#' @return Coefficient of variation or NA
#' @author Fredrik Karlsson
#' @export
#' @examples
#' x <- c(1.2, 1.5, 1.3, 1.4, 1.6)
#' cpp_cov(x)
cpp_cov <- function(x, na_rm = TRUE) {
    .Call(`_articulated_cpp_cov`, x, na_rm)
}

#' Relative Coefficient of Variation (intervals 5-n vs 1-4)
#' 
#' Computes the coefficient of variance for intervals 5-n relative to 
#' the mean duration of intervals 1-4, as described in Skodda et al. (2012).
#' 
#' @param x Vector of syllable durations
#' @param n Number of intervals to include (default 20)
#' @param return_na Return NA if insufficient data? (default TRUE)
#' @param na_rm Remove NA values before computation? (default TRUE)
#' @return Relative COV or NA
#' @author Fredrik Karlsson
#' @export
#' @references
#' Skodda, S., Lorenz, J., & Schlegel, U. (2012). Instability of syllable 
#' repetition in Parkinson's disease. Basal Ganglia, 3(1), 33-37.
#' @examples
#' durations <- runif(25, 0.1, 0.3)
#' cpp_cov5_x(durations)
cpp_cov5_x <- function(x, n = 20L, return_na = TRUE, na_rm = TRUE) {
    .Call(`_articulated_cpp_cov5_x`, x, n, return_na, na_rm)
}

#' Raw pairwise variability index.
#' 
#' Computes the raw Pairwire Variability Index (rPVI) on a supplied vector of durations.
#' 
#' @author Fredrik Karlsson
#' @export
#' 
#' @param x A vector of durations in arbitrary unit.
#' @param omit Boolean indicating whether NA values should be removed before calculating rPVI.
#' 
#' @return A single value representing the rPVI for the vector of durations
#' 
#' @references Nolan, F., & Asu, E. L. (2009). The Pairwise Variability Index and Coexisting Rhythms in Language. Phonetica, 66(1-2), 64–77. doi:10.1159/000208931 
#' @name rPVI
NULL

#' Normalized pairwise variability index.
#' 
#' Computes the normalized Pairwire Variability Index (nPVI) on a supplied vector of durations.
#' 
#' @author Fredrik Karlsson
#' @export
#' 
#' @param x A vector of durations in arbitrary unit.
#' @param omit Boolean indicating whether NA values should be removed before calculating nPVI.
#' 
#' @return A single value reprenting the nPVI for the vector of durations
#' 
#'@references Nolan, F., & Asu, E. L. (2009). The Pairwise Variability Index and Coexisting Rhythms in Language. Phonetica, 66(1-2), 64–77. doi:10.1159/000208931 
#'@name nPVI
NULL

#' Computes the local jitter of a vector.
#' 
#' @author Fredrik Karlsson
#' @export
#' 
#' @param x The input vector
#' @param min.period The minimum value to be included in the calculation.
#' @param max.period The maximum value to be included in the calculation.
#' @param absolute Should the (local) Jitter value be returned (absolute=FALSE), or the absolute (local) Jitter (absolute=TRUE). In the case of absolute (local) Jitter, the jitter will *not* be devided by the average period.
#' @param omit Should missing intervals be removed?
#' 
#' @return A value indicating the (local) jitter (absolute=FALSE) or the absolute (local) jitter (absolute=TRUE).
#' @name jitter_local
NULL

#' Computes the Difference of Differences of Periods (DDP) of a vector.
#' 
#' @author Fredrik Karlsson
#' @export
#' 
#' @param x The input vector
#' @param min.period The minimum value to be included in the calculation.
#' @param max.period The maximum value to be included in the calculation.
#' @param absolute Should the Jitter DDP value be returned (absolute=FALSE), or the absolute Jitter DDP (absolute=TRUE). 
#' In the case of absolute Jitter DDP, the jitter will *not* be devided by the average period.
#' @param omit Should missing intervals be removed?
#' 
#' @return The Jitter DDP (in s) (absolute=FALSE) or the absolute jitter DDP (in percent, $1..600%$) (absolute=TRUE). If the vector contains less than three values, NA is returned.
#' @name jitter_ddp
#' 
NULL

#' Computes the Relative Average Perturbation (RAP) of a vector.
#' 
#' @author Fredrik Karlsson
#' @export
#' 
#' @param x The input vector
#' @param min.period The minimum value to be included in the calculation.
#' @param max.period The maximum value to be included in the calculation.
#' @param absolute Should the Jitter RAP value be returned (absolute=FALSE), or the absolute Jitter RAP(absolute=TRUE). In the case of absolute Jitter RAP, the jitter will *not* be devided by the average period. 
#' @param omit Should missing intervals be removed?
#' 
#' @name jitter_rap
#' 
#' @return The RAP (in percent, $1..200%$) or absolute PPQ5 (\code{absAP}) values (in s) for the vector of values. If the vector contains less than three values, NA is returned.
NULL

#' Computes the five-point Period Perturbation Quotient (PPQ5) of a vector.
#' 
#' @author Fredrik Karlsson
#' @export
#'  
#' @param x The input vector
#' @param min.period The minimum value to be included in the calculation.
#' @param max.period The maximum value to be included in the calculation.
#'  @param absolute Should the Jitter RAP value be returned (absolute=FALSE), or the absolute Jitter PPQ5 (absolute=TRUE). In the case of absolute Jitter PPQ5, the jitter will *not* be devided by the average period. 
#' @param omit Should missing intervals be removed?
#' 
#' @name jitter_ppq5
#' 
#' @return Either the jitter PPQ5 (in percent, 1..400%) or the absolute PPQ5 values (in s, 1..4) for the vector of values. If the vector contains less than five values, NA is returned.
NULL

rPVI <- function(x, omit = FALSE) {
    .Call(`_articulated_rPVI`, x, omit)
}

nPVI <- function(x, omit = FALSE) {
    .Call(`_articulated_nPVI`, x, omit)
}

jitter_local <- function(x, minperiod, maxperiod, absolute = FALSE, omit = FALSE) {
    .Call(`_articulated_jitter_local`, x, minperiod, maxperiod, absolute, omit)
}

jitter_ddp <- function(x, minperiod, maxperiod, absolute = FALSE, omit = FALSE) {
    .Call(`_articulated_jitter_ddp`, x, minperiod, maxperiod, absolute, omit)
}

jitter_rap <- function(x, minperiod, maxperiod, absolute = FALSE, omit = FALSE) {
    .Call(`_articulated_jitter_rap`, x, minperiod, maxperiod, absolute, omit)
}

jitter_ppq5 <- function(x, minperiod, maxperiod, absolute = FALSE, omit = FALSE) {
    .Call(`_articulated_jitter_ppq5`, x, minperiod, maxperiod, absolute, omit)
}

cppRelStab <- function(x, start = 5L, end = 12L, omit = FALSE) {
    .Call(`_articulated_cppRelStab`, x, start, end, omit)
}

#' Identify missing or invalid values in numeric vector
#' 
#' Identifies values that are NA, NULL, or below/equal to a threshold.
#' 
#' @param x Numeric vector
#' @param what_na Threshold value (values <= this are considered missing)
#' @return Logical vector indicating missing values
#' @author Fredrik Karlsson
#' @export
#' @examples
#' x <- c(1.2, 0, 1.5, NA, -1, 2.0)
#' cpp_missing_vec_numeric(x, what_na = 0)
cpp_missing_vec_numeric <- function(x, what_na = 0.0) {
    .Call(`_articulated_cpp_missing_vec_numeric`, x, what_na)
}

#' Identify missing or invalid values in character vector
#' 
#' Identifies values that are NA or match specified strings.
#' 
#' @param x Character vector
#' @param what_na Character vector of values to consider missing
#' @return Logical vector indicating missing values
#' @author Fredrik Karlsson
#' @export
#' @examples
#' x <- c("a", "missing", "b", NA, "c")
#' cpp_missing_vec_character(x, c("missing", ""))
cpp_missing_vec_character <- function(x, what_na) {
    .Call(`_articulated_cpp_missing_vec_character`, x, what_na)
}

#' Compute fraction of missing values
#' 
#' Calculates the proportion of values that are missing or invalid.
#' 
#' @param x Numeric vector
#' @param what_na Threshold for missing values
#' @return Fraction of missing values (0 to 1)
#' @author Fredrik Karlsson
#' @export
#' @examples
#' x <- c(1.2, 0, 1.5, NA, -1, 2.0)
#' cpp_missing_frac(x)
cpp_missing_frac <- function(x, what_na = 0.0) {
    .Call(`_articulated_cpp_missing_frac`, x, what_na)
}

#' Find first changepoint in missing value pattern
#' 
#' Identifies the index of the first transition between missing and 
#' non-missing values (or vice versa).
#' 
#' @param x Numeric vector
#' @param what_na Threshold for missing values
#' @return Index of first changepoint (1-based) or NA if no changepoint
#' @author Fredrik Karlsson
#' @export
#' @examples
#' x <- c(0, 0, 1.2, 1.5, 2.0)
#' cpp_left_changepoint(x)  # Returns 3
cpp_left_changepoint <- function(x, what_na = 0.0) {
    .Call(`_articulated_cpp_left_changepoint`, x, what_na)
}

#' Find last changepoint in missing value pattern
#' 
#' Identifies the index of the last transition between missing and
#' non-missing values (or vice versa).
#' 
#' @param x Numeric vector
#' @param what_na Threshold for missing values
#' @return Index of last changepoint (1-based) or NA if no changepoint
#' @author Fredrik Karlsson
#' @export
#' @examples
#' x <- c(0, 0, 1.2, 1.5, 0, 0)
#' cpp_right_changepoint(x)  # Returns 5
cpp_right_changepoint <- function(x, what_na = 0.0) {
    .Call(`_articulated_cpp_right_changepoint`, x, what_na)
}

#' Compute slope of linear regression
#' 
#' Fits a simple linear regression y ~ x and returns the slope coefficient.
#' NA values are automatically removed.
#' 
#' @param y Response vector
#' @param what_na Threshold for missing values
#' @return Slope coefficient or NA if insufficient data
#' @author Fredrik Karlsson
#' @export
#' @examples
#' y <- c(1.0, 1.5, 2.0, 2.3, 3.0)
#' cpp_lm_slope(y)
cpp_lm_slope <- function(y, what_na = 0.0) {
    .Call(`_articulated_cpp_lm_slope`, y, what_na)
}

#' Compute peak prominence (maximum residual from linear trend)
#' 
#' Fits a linear regression and returns the maximum positive residual,
#' which represents the most prominent peak above the trend line.
#' 
#' @param y Response vector
#' @param what_na Threshold for missing values
#' @return Maximum residual or NA if insufficient data
#' @author Fredrik Karlsson
#' @export
#' @examples
#' y <- c(1.0, 1.5, 3.0, 2.0, 2.5)  # Peak at index 3
#' cpp_peak_prominence(y)
cpp_peak_prominence <- function(y, what_na = 0.0) {
    .Call(`_articulated_cpp_peak_prominence`, y, what_na)
}

#' Compute vowel space center
#' 
#' Computes the center of a vowel space using different methods.
#' 
#' @param f1 F1 formant values (Hz)
#' @param f2 F2 formant values (Hz)
#' @param method Center computation method: "centroid", "twomeans", or "wcentroid"
#' @param na_rm Remove NA values? (default TRUE)
#' @return List with f1c and f2c center coordinates
#' @author Fredrik Karlsson
#' @export
#' @examples
#' f1 <- c(300, 600, 600, 300)
#' f2 <- c(2200, 1700, 1000, 900)
#' cpp_vowel_center(f1, f2)
cpp_vowel_center <- function(f1, f2, method = "wcentroid", na_rm = TRUE) {
    .Call(`_articulated_cpp_vowel_center`, f1, f2, method, na_rm)
}

#' Compute vowel vector norms (distances from center)
#' 
#' Computes the Euclidean distance of each vowel from the vowel space center.
#' 
#' @param f1 F1 formant values (Hz)
#' @param f2 F2 formant values (Hz)
#' @param f1c F1 coordinate of vowel space center
#' @param f2c F2 coordinate of vowel space center
#' @return Vector of Euclidean distances
#' @author Fredrik Karlsson
#' @export
#' @examples
#' f1 <- c(300, 600, 600, 300)
#' f2 <- c(2200, 1700, 1000, 900)
#' center <- cpp_vowel_center(f1, f2)
#' cpp_vowel_norms(f1, f2, center$f1c, center$f2c)
cpp_vowel_norms <- function(f1, f2, f1c, f2c) {
    .Call(`_articulated_cpp_vowel_norms`, f1, f2, f1c, f2c)
}

#' Compute vowel vector angles (polar coordinates)
#' 
#' Computes the angle of each vowel vector from the vowel space center,
#' in radians using atan2.
#' 
#' @param f1 F1 formant values (Hz)
#' @param f2 F2 formant values (Hz)
#' @param f1c F1 coordinate of vowel space center
#' @param f2c F2 coordinate of vowel space center  
#' @return Vector of angles in radians (-pi to pi)
#' @author Fredrik Karlsson
#' @export
#' @examples
#' f1 <- c(300, 600, 600, 300)
#' f2 <- c(2200, 1700, 1000, 900)
#' center <- cpp_vowel_center(f1, f2)
#' cpp_vowel_angles(f1, f2, center$f1c, center$f2c)
cpp_vowel_angles <- function(f1, f2, f1c, f2c) {
    .Call(`_articulated_cpp_vowel_angles`, f1, f2, f1c, f2c)
}

